image: etnyx88/docker-test-env

stages:
  - deploy

github_mirror:
  stage: deploy
  script:
    - apt-get update -yqq
    - apt-get install git -yqq
    - git push --mirror https://$GITHUB_USER:$GITHUB_PASS@github.com/ETNyx88/docker-test-env.git
